services:

  backend:
    build: .
    container_name: djangoRest
    volumes:
      - ./conf:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY="test"
    